fix: ensure page is secure with Chrome >= 72
clappr/clappr-chromecast-plugin pull request #39
Opened 2019-02-07 16:46 UTC by kslimani

Chrome version 72 require a secure https url.

Source: [https://plus.google.com/+LeonNicholls/posts/jhTafR5dhGC](https://plus.google.com/+LeonNicholls/posts/jhTafR5dhGC)

This fix ensure that page is secure if chrome is greater than or equals to 72. _(otherwise attempt to boot cast api, and therefore is backward compatible)_.

2019-02-07 21:57 UTC, towerz requested changes
Aside from a small style issue, there's nothing else to be changed.

2019-02-07 21:57 UTC, towerz commented on src/chromecast.js
> +  {
Just a small style issue here, could you please fix this?

2019-02-07 23:00 UTC, kslimani commented on src/chromecast.js
> +  {
Nice catch! should be fixed.

2019-02-08 21:23 UTC, towerz approved these changes

2019-02-08 21:23 UTC, merged